spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dbcosta/config-server-repo
          #file://Users//belinda//Documents//Projects//microservices//config-server-repo
  application:
    name: spring-cloud-config-server
server:
  port: 8888
management:
  security:
    enabled: false